version: '3.1'

services:
  db_postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: trocado
    volumes:
      - .\D:\Trocado:\tmp
    ports: ['5432:5432']
